name: Terraform plan on pull request

permissions:
    id-token: write
    contents: write
    checks: write
    pull-requests: read

on:
    pull_request:
        branches: [main]

jobs:
    pre_commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Pre commit
              uses: ./.github/actions/pre_commit
              with:
                python_version: "3.10"

    dev:
        runs-on: ubuntu-latest
        needs: [pre_commit]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Terraform plan
              uses: ./.github/actions/run_terraform
              with:
                command: plan
                environment: dev
                tfc_token: ${{ secrets.TFC_TOKEN }}

    # prd:
    #     runs-on: ubuntu-latest
    #     needs: [pre_commit]
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4

    #         - name: Terraform plan
    #           uses: ./.github/actions/run_terraform
    #           with:
    #             command: plan
    #             environment: prd
    #             tfc_token: ${{ secrets.TFC_TOKEN }}
